#!/usr/bin/env python3

import dotenv
import os
import discord
from discord.ext import commands

# Get the token from the .env file
dotenv.load_dotenv()
TOKEN = os.getenv('TOKEN')

bot = discord.Client(intents=discord.Intents.all())

@bot.event
async def on_ready():
    print(f'{bot.user} has connected to Discord!')

@bot.event
async def on_message(message):
    author: discord.Member = message.author
    if author == bot.user:
        return
    if type(author) == discord.User:
        return
    if author.guild_permissions.manage_messages:
        return
    if ".com" in message.content or ".net" in message.content or ".org" in message.content or ".gg" in message.content:
        await message.delete()

bot.run(TOKEN)
